RESET = "RESET"

## DB ACTIONS
LOAD_LAPTOPS = "LOAD_LAPTOPS"
UPDATE_LAPTOPS = "UPDATE_LAPTOPS"
UPDATE_CENTER_LAPTOPS = "UPDATE_CENTER_LAPTOPS"

## LANG ACTIONS
EXTRACT_NAME = "EXTRACT_NAME"
EXTRACT_REQUIREMENTS = "EXTRACT_REQUIREMENTS"
LOOK_FOR_REQUIREMENT = "LOOK_FOR_REQUIREMENT"
LOOK_FOR_REQUIREMENT_RESPONSE = "LOOK_FOR_REQUIREMENT_RESPONSE"
LOOK_FOR_EDGE_COMPUTERS = "LOOK_FOR_EDGE_COMPUTERS"
LOOK_FOR_EDGE_COMPUTERS_RESPONSE = "LOOK_FOR_EDGE_COMPUTERS_RESPONSE"
INSERT_REQUIREMENTS = "INSERT_REQUIREMENTS"
INSERT_REQUIREMENTS_RESPONSE = "INSERT_REQUIREMENTS_RESPONSE"

LOOK_FOR_COMPUTERS_RECOMMEND = "LOOK_FOR_COMPUTERS_RECOMMEND"
LOOK_FOR_COMPUTERS_RECOMMEND_RESPONSE = "LOOK_FOR_COMPUTERS_RECOMMEND_RESPONSE"
