WELCOME = "WELCOME"
ASK_NAME = "ASK_NAME"
ASK_NAME_AGAIN = "ASK_NAME_AGAIN"
NAME_ASKED = "NAME_ASKED"
WELCOME_NAME = "WELCOME_NAME"

ASK_REQUIREMENTS = "ASK_REQUIREMENTS"
ASK_REQUIREMENTS_AGAIN = "ASK_REQUIREMENTS_AGAIN"
REQUIREMENTS_ASKED = "REQUIREMENTS_ASKED"

CONFIRM_REQUIREMENTS = "CONFIRM_REQUIREMENTS"
WAIT_CONFIRM_REQUIREMENTS = "WAIT_CONFIRM_REQUIREMENTS"

LOOK_FOR_REQUIREMENTS = "LOOK_FOR_REQUIREMENTS"
LOOK_FOR_EDGE_COMPUTERS = "LOOK_FOR_EDGE_COMPUTERS"
SHOW_EDGE_COMPUTERS = "SHOW_EDGE_COMPUTERS"

ASK_EDGE_COMPUTER = "ASK_EDGE_COMPUTER"

RECOMMEND_COMPUTER = "RECOMMEND_COMPUTER"
